### ISSUE TITLE
BUG: Chat interface reopening will not load history

### ISSUE THREAD

**Issue by immortal521** [Kurama622/llm.nvim#10]
The history file can be saved successfully, but the history list is only current

**Comment by Kurama622** [comment]
`<C-j>`/`<C-k>` to switch history

**Comment by immortal521** [comment]
> `<C-j>`/`<C-k>` to switch history
> 
> 

There is only one current in the history list, and there is no content in the current. The previous history has saved files, but it is not displayed in the history list.

**Comment by Kurama622** [comment]
Get history list cmd: `ls -At <your history path>  2>/dev/null`

How do you use neovim on Windows, maybe this cmd window cannot be executed?

I can also modify such commands to be system-independent.

**Comment by immortal521** [comment]
`ls` is not supported in Windows cmd, and the `ls` command of powershell does not have the `-At` parameter

**Comment by Kurama622** [comment]
I will get the history list by lua api.

Until I update, maybe you can use a terminal like cmder to use neovim （It comes with some Linux commands）



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/11/2024 00:06 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Kurama622/llm.nvim] BUG: Chat interface reopening will not load history (Issue #10) |

ls is not supported in Windows cmd, and the ls command of powershell does not have the -At parameter

**Comment by Kurama622** [comment]
Updated, try switching to the Windows branch.

**Comment by immortal521** [comment]
This bug has been fixed, but there are some other problems. Should I start a new issue or just say it here?

**Comment by Kurama622** [comment]
Close resolved issues, create a new issue



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/12/2024 22:44 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Kurama622/llm.nvim] BUG: Chat interface reopening will not load history (Issue #10) |

This bug has been fixed, but there are some other problems. Should I start a new issue or just say it here?
