### ISSUE TITLE
请问，是否支持 兼容 OpenAI的 DeepSeek？

### ISSUE THREAD

**Issue by tieniu1** [Kurama622/llm.nvim#16]
作者你好，我在b站看到你的视频，感谢你的工作。
但是我碰到了一些问题，希望能得到你的回复。

我为llm.nvim配置了DeepSeek，但是AI并没有工作，也没有任何报错。
![Clip_2024-12-15_19-18-51](https://github.com/user-attachments/assets/87856813-6396-420e-a0f5-003e6120a9f6)

我在.zshrc中配置了 `$LLM_KEY` 使用 `sourc ~/.zshrc` 更新了配置。在终端中curl请求DeepSeek使用 `$LLM_KEY`可以正常工作，在neovim中使用 `:echo $LLM_KEY` 也可以打印出配置的key。

DeepSeek API 兼容 OpenAI，之前在其他AI工具中使用过DeepSeek。

![Clip_2024-12-15_19-19-43](https://github.com/user-attachments/assets/8d4be351-e791-4eb5-9045-54df489efd75)

**Comment by Kurama622** [comment]
是Preview窗口只有你的输入，没有大模型的输出吗

**Comment by tieniu1** [comment]
> 是Preview窗口只有你的输入，没有大模型的输出吗

是的

**Comment by Kurama622** [comment]
![image](https://github.com/user-attachments/assets/8006f403-4c2c-4d26-b691-2b39f224d3c0)

我这里是正常的，我的配置：
```lua
        url = "https://api.deepseek.com/chat/completions",
        model = "deepseek-chat",
        api_type = "openai",
        max_tokens = 4096,
```

**Comment by tieniu1** [comment]
谢谢你，我设置max_tokens=4096也能工作了。
![Clip_2024-12-15_20-01-42](https://github.com/user-attachments/assets/c1322b04-63bb-4e78-b95f-f9da4872f789)

查了一下文档，是DeepSeek的限制导致的。
![Clip_2024-12-15_19-59-51](https://github.com/user-attachments/assets/3df2286f-3796-441e-952c-527a2a23a1f2)

**Comment by tieniu1** [comment]
> ![image](https://private-user-images.githubusercontent.com/41457394/395859336-8006f403-4c2c-4d26-b691-2b39f224d3c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjQ0NDAsIm5iZiI6MTczNDI2NDE0MCwicGF0aCI6Ii80MTQ1NzM5NC8zOTU4NTkzMzYtODAwNmY0MDMtNGMyYy00ZDI2LWI2OTEtMmIzOWYyMjRkM2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDEyMDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhN2UwYzk4MmFmODljYTFlOWZjN2EwODRlZmJlN2I2MGMxODYyMzA1ZTAyNTdlNzJiNjgwNjJkYWMyYTNhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fSqpjMw-OXcet6AmcG4-0JAzY1APAZa56Ivz3NM855I)
> 
> 我这里是正常的，我的配置：
> 
> ```lua
>         url = "https://api.deepseek.com/chat/completions",
>         model = "deepseek-chat",
>         api_type = "openai",
>         max_tokens = 4096,
> ```

谢谢你，我设置max_tokens=4096也能工作了。
![Clip_2024-12-15_20-01-42](https://github.com/user-attachments/assets/c1322b04-63bb-4e78-b95f-f9da4872f789)

查了一下文档，是DeepSeek的限制导致的。
![Clip_2024-12-15_19-59-51](https://github.com/user-attachments/assets/3df2286f-3796-441e-952c-527a2a23a1f2)

**Comment by Kurama622** [comment]
好，解决了就好
