### ISSUE TITLE
无法调用tools.lua里的函数

### ISSUE THREAD

**Issue by Yugikira** [Kurama622/llm.nvim#17]
操作系统：windows
NVIM v0.10.0-dev-2867+g7aa56370f
Build type: RelWithDebInfo      
LuaJIT 2.1.1710088188

我在参考中文说明文档给不同的handler配置不同的AI后，得到下面的提示
![微信图片_20241216003504](https://github.com/user-attachments/assets/3358986b-bee3-4479-85a0-826b1103793d)

然后chat窗口就无法提交信息，也没有办法正常使用。请问这个问题应该怎么解决？

另外，每次都要先手动:LLMSessionToggle报错一次，才能正确调用。

**Comment by Kurama622** [comment]
应该是没有加这一句
local​ ​tools​ ​=​ ​require​(​"​llm.common.tools​"​)
你先看我的配置文件吧
https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm.lua

中文文档还没写完，会有点问题

**Comment by Kurama622** [comment]
临时修了一下：https://github.com/Kurama622/llm.nvim/blob/main/README_CN.md#ai%E5%B7%A5%E5%85%B7%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by Kurama622** [comment]
这种switch("enable_gpt")你先不要用，这个是我在shell中定义了一些东西，这一块的文档还没有写
```lua
              fetch_key = function()
                return switch("enable_gpt")
              end,
```
你可以直接
```lua
              fetch_key = function()
                return "your api key"
              end,
```

**Comment by Yugikira** [comment]
谢谢大佬，参考你的配置修改好了。fetch_key 那里我改了，直接用os.getenv()。

**Comment by Kurama622** [comment]
好，我应该说明一下中文文档还在撰写中，没写完就传上来是我的问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月16日 01:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kurama622/llm.nvim] 无法调用tools.lua里的函数 (Issue #17) |

谢谢大佬，参考你的配置修改好了。fetch_key 那里我改了，直接用os.getenv()。
