### ISSUE TITLE
kimi调用失败

### ISSUE THREAD

**Issue by name-jerry** [Kurama622/llm.nvim#2]
复制[kimi配置](https://github.com/Kurama622/llm.nvim/wiki/Modify-LLM#kimi)之后使用<leader>ae失败
![1729065095486](https://github.com/user-attachments/assets/06c0df31-b177-4022-adf0-d2bea281f048)

**Comment by Kurama622** [comment]
1. 你可能没有配置LLM_KEY （可以在https://platform.moonshot.cn/docs/intro#%E8%8E%B7%E5%8F%96-api-%E5%AF%86%E9%92%A5 上面获取kimi的api key）
2. 你在bashrc或者zshrc中配置了LLM_KEY，但是没有source ~/.bashrc或者source ~/.zshrc，所以LLM_KEY没有生效
前两点应该可以解决你的问题

最后，你可以参考我的配置：https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm.lua 直接指定 api_type = "openai", 而不用自定义streaming_handler, 这种方式会看起来更加简洁

**Comment by name-jerry** [comment]
> 1. 你可能没有配置LLM_KEY （可以在https://platform.moonshot.cn/docs/intro#%E8%8E%B7%E5%8F%96-api-%E5%AF%86%E9%92%A5 上面获取kimi的api key）
> 2. 你在bashrc或者zshrc中配置了LLM_KEY，但是没有source ~/.bashrc或者source ~/.zshrc，所以LLM_KEY没有生效
>    前两点应该可以解决你的问题
> 
> 最后，你可以参考我的配置：https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm.lua 直接指定 api_type = "openai", 而不用自定义streaming_handler, 这种方式会看起来更加简洁

谢谢，我还在好奇为什么不用登陆账号呢
