### ISSUE TITLE
智谱清言

### ISSUE THREAD

**Issue by kdurant** [Kurama622/llm.nvim#20]
bashrc里配置好了KEY
![image](https://github.com/user-attachments/assets/f83e0e63-9964-43f8-af68-2e2fcfae3557)

插件配置如下
```lua
    {
        "Kurama622/llm.nvim",
        dependencies = { "nvim-lua/plenary.nvim", "MunifTanjim/nui.nvim" },
        cmd = { "LLMSesionToggle", "LLMSelectedTextHandler" },
        config = function()
            require("llm").setup({
                max_tokens = 1024,
                url = "https://open.bigmodel.cn/api/paas/v4/chat/completions",
                model = "glm-4-flash",
                prefix = {
                    user = { text = "😃 ", hl = "Title" },
                    assistant = { text = "⚡ ", hl = "Added" },
                },

                save_session = true,
                max_history = 15,

        -- stylua: ignore
        keys = {
          -- The keyboard mapping for the input window.
          ["Input:Submit"]      = { mode = "n", key = "<cr>" },
          ["Input:Cancel"]      = { mode = "n", key = "<C-c>" },
          ["Input:Resend"]      = { mode = "n", key = "<C-r>" },

          -- only works when "save_session = true"
          ["Input:HistoryNext"] = { mode = "n", key = "<C-j>" },
          ["Input:HistoryPrev"] = { mode = "n", key = "<C-k>" },

          -- The keyboard mapping for the output window in "split" style.
          ["Output:Ask"]        = { mode = "n", key = "i" },
          ["Output:Cancel"]     = { mode = "n", key = "<C-c>" },
          ["Output:Resend"]     = { mode = "n", key = "<C-r>" },

          -- The keyboard mapping for the output and input windows in "float" style.
          ["Session:Toggle"]    = { mode = "n", key = "<leader>ac" },
          ["Session:Close"]     = { mode = "n", key = "<esc>" },
        },
            })
        end,
        keys = {
            { "<leader>ac", mode = "n", "<cmd>LLMSessionToggle<cr>" },
            { "<leader>ae", mode = "v", "<cmd>LLMSelectedTextHandler 请解释下面这段代码<cr>" },
            { "<leader>t", mode = "x", "<cmd>LLMSelectedTextHandler 英译汉<cr>" },
        },
    },
```

但`<leader>ac`后输入问题，啥反应都没有

**Comment by Kurama622** [comment]
LLM_KEY生效了吗，我copy了你的配置，没有问题

**Comment by kdurant** [comment]
![image](https://github.com/user-attachments/assets/d3d180bb-7708-46a3-9948-458894798757)
这里没有问题了

**Comment by Kurama622** [comment]
你的key怎么这么短，应该有49个字符

**Comment by Kurama622** [comment]
https://bigmodel.cn/usercenter/proj-mgmt/apikeys  这个链接创建api key

**Comment by kdurant** [comment]
![image](https://github.com/user-attachments/assets/1c54341c-604d-46ba-a347-7331763c54a6)
用这个了，还是不行

**Comment by Kurama622** [comment]
+QQ: 1651843412 我看看具体啥情况

**Comment by Kurama622** [comment]
> ![image](https://private-user-images.githubusercontent.com/2704364/399166617-1c54341c-604d-46ba-a347-7331763c54a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODI3NTgsIm5iZiI6MTczNTQ4MjQ1OCwicGF0aCI6Ii8yNzA0MzY0LzM5OTE2NjYxNy0xYzU0MzQxYy02MDRkLTQ2YmEtYTM0Ny03MzMxNzYzYzU0YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjlUMTQyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY0NDMxM2M4MGM3ZjNjOTRlNmQxMGUxNzFmYmJkYjBhYTZjZjY2ODkxYzQxYjBmNWZlOTFhNDIxMWU2ODNhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OWWSMaR3w9Go2qGPvEC5vVdy_1gu9yYvmRMkpbTOugI) 用这个了，还是不行

source ~/.bashrc 了吗

**Comment by Kurama622** [comment]
![image](https://github.com/user-attachments/assets/69301a82-2710-4622-b1be-059fee614ec0)
我这边配了api key，source以后是正常的。
如果你source了也不正常，贴一下你的系统信息。window的curl需要特殊处理

**Comment by kdurant** [comment]
ubuntu22.04
我加你qq了

**Comment by Kurama622** [comment]
根据你的配置：insert 模式下回车是输入多行文本，normal模式下回车是提交问题
