### ISSUE TITLE
BUG:  Floating window didn't stretch after resize.

### ISSUE THREAD

**Issue by boydaihungst** [Kurama622/llm.nvim#4]
Floating window didn't stretch after resize.

![image](https://github.com/user-attachments/assets/7dc95993-916a-4a9c-aa42-dbed25c58151)

**Comment by Kurama622** [comment]
> Floating window didn't stretch after resize.
> 
> ![image](https://github.com/user-attachments/assets/7dc95993-916a-4a9c-aa42-dbed25c58151)
> 

Maybe I should add a vimresize event. I'm going to fix it, but it may take some time as I'm sick right now. Thank you for your feedback.

**Comment by boydaihungst** [comment]
Take care of yourself first. 👍

**Comment by Kurama622** [comment]
I've made a simple fix, take a look and see if it's okay.

**Comment by boydaihungst** [comment]
Confirm that it's fixed
