### ISSUE TITLE
feature request.

### ISSUE THREAD

**Issue by cxwx** [Kurama622/llm.nvim#6]
API 不实用环境变量，直接写在 config 里面可以吗？ opt= {api_key=...}

**Comment by Kurama622** [comment]
这样你的配置文件不就不能用git管理了吗，否则所有人都能看到key。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月25日 23:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Kurama622/llm.nvim] feature request. (Issue #6) |

API 不实用环境变量，直接写在 config 里面可以吗？ opt= {api_key=...}

**Comment by Kurama622** [comment]
很简单，直接这样配置就好
```lua
fetch_key = function()
    return <you api key>
end,
```
这是我的配置文件：[https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm.lua](https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm.lua)  你可以参考一下。

在我的配置文件中，你可以看到enable_glm或者enable_gpt这样的字眼，这个正好可以回答你提到的所有的provider使用同样的环境变量这个问题。我其实会创建一个.env文件来记录所有的key，智谱和openai是不同的变量，通过enable_provider_name来决定LLM_KEY被赋予哪个平台的key。
