### ISSUE TITLE
翻译中文字符时出现报错

### ISSUE THREAD

**Issue by shy-robin** [Kurama622/llm.nvim#8]
Hi，大佬，非常感谢你的插件，很有用！

但我在使用「翻译」这个功能时，出现了点问题。

在 visual mode 下，使用 `<leader>at` 进行翻译，如果选中的是英文字符，可以正常运行，如果是中文字符就会报错。

具体报错信息如下：
```
Error executing Lua callback: Vim:E474: 字符串 "<e6>" 包含不起始任何 UTF-8 字符的字节
stack traceback:
	[C]: in function 'json_encode'
	...al/share/nvim/lazy/llm.nvim/lua/llm/common/streaming.lua:104: in function 'GetStreamingOutput'
	...obin/.local/share/nvim/lazy/llm.nvim/lua/llm/session.lua:38: in function 'LLMSelectedTextHandler'
	.../shyrobin/.local/share/nvim/lazy/llm.nvim/plugin/llm.lua:6: in function <.../shyrobin/.local/share/nvim/lazy/llm.nvim/plugin/llm.lua:5>

```

这是录屏：

https://github.com/user-attachments/assets/dc1f19a8-bb6e-4061-87fc-6d5cb0581cac

另外，还有个问题就是出现报错后，使用 `<esc>` 无法关闭浮动窗口。

这两个问题能帮忙看下吗？😘

**Comment by Kurama622** [comment]
好，我修复一下。之前没考虑翻译中文的情况。
目前这种esc无法关闭窗口的情况，可以聚焦到那个窗口，：q关闭。后面我也会处理一下这种情况





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月06日 14:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Kurama622/llm.nvim] 翻译中文字符时出现报错 (Issue #8) |

Hi，大佬，非常感谢你的插件，很有用！

但我在使用「翻译」这个功能时，出现了点问题。

在 visual mode 下，使用 <leader>at 进行翻译，如果选中的是英文字符，可以正常运行，如果是中文字符就会报错。

具体报错信息如下：

Error executing Lua callback: Vim:E474: 字符串 "<e6>" 包含不起始任何 UTF-8 字符的字节
stack traceback:
	[C]: in function 'json_encode'
	...al/share/nvim/lazy/llm.nvim/lua/llm/common/streaming.lua:104: in function 'GetStreamingOutput'
	...obin/.local/share/nvim/lazy/llm.nvim/lua/llm/session.lua:38: in function 'LLMSelectedTextHandler'
	.../shyrobin/.local/share/nvim/lazy/llm.nvim/plugin/llm.lua:6: in function <.../shyrobin/.local/share/nvim/lazy/llm.nvim/plugin/llm.lua:5>



这是录屏：

https://github.com/user-attachments/assets/dc1f19a8-bb6e-4061-87fc-6d5cb0581cac

另外，还有个问题就是出现报错后，使用 <esc> 无法关闭浮动窗口。

这两个问题能帮忙看下吗？😘

**Comment by shy-robin** [comment]
好的，感谢大佬！
另外，我还想提几点优化建议：
1. 支持光标切换到 `Preview` 和 `History` 面板（因为我想复制一些文本内容，或者可以直接打开对应的会话文件也行）；
2. 支持修改当前会话名称
3. 支持定位到会话对应的文件里（比如查看一些历史数据之类的）
4. 支持手动创建或者删除会话
5. 再次打开 chat 时可以定位到上次的会话里（现状是定位到一个 current 会话上）
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/6fa0e012-26b9-4299-95e9-4951a8364cfe">

**Comment by Kurama622** [comment]
目前ctrl w按两次两次在窗口间跳转，你是觉得这样不太方便是吗

history那里按ctrl j/k可以直接切换会话

你说的定位到会话对应的文件里查看历史数据是什么意思，因为切换会话的时候，历史数据就会被预览，这个我没太理解你的意思

你提的这些建议挺好的，我会考虑添加一些，感谢分享宝贵意见😃




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月06日 15:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kurama622/llm.nvim] 翻译中文字符时出现报错 (Issue #8) |

好的，感谢大佬！
另外，我还想提几点优化建议：

支持光标切换到 Preview 和 History 面板（因为我想复制一些文本内容，或者可以直接打开对应的会话文件也行）；
支持修改当前会话名称
支持定位到会话对应的文件里（比如查看一些历史数据之类的）
支持手动创建或者删除会话
再次打开 chat 时可以定位到上次的会话里（现状是定位到一个 current 会话上）
image.png (view on web)

**Comment by shy-robin** [comment]
哦哦，`<C-w>` 这种跳转我不太常用，我一般使用 `<C-h/j/k/k>` 进行窗口跳转的，这个我注意一下。

查看历史数据那个问题，我理解这些会话数据都是存放在本地文件里的，所以我就想知道能不能自动定位到那个文件或者输出对应文件的路径，方便我查找。

**Comment by Kurama622** [comment]
保存路径你是可以配置的：`history_path = "/tmp/llm-history",` 默认在`$HOME/.local/state/nvim/llm-history`

**Comment by Kurama622** [comment]
中文字符的bug已经修复了

**Comment by shy-robin** [comment]
已经修复了，非常感谢😘！

**Comment by Kurama622** [comment]
你现在用的这个弹窗翻译，是流式输出的版本，但是这种方式窗口大小是固定的，我感觉特别丑。所以后面我开发了一版弹性窗口，根据内容多少调整窗口大小。如果你有兴趣也可以体验一下：
```lua
        spinner = {
          text = {
            "󰧞󰧞",
            "󰧞󰧞",
            "󰧞󰧞",
            "󰧞󰧞",
          },
          hl = "Title",
        },

        app_handler = {
          WordTranslate = {
            handler = tools.flexi_handler,
            prompt = "Translate the following text to Chinese, please only return the translation",
            opts = {
              exit_on_move = true,
              enter_flexible_window = false,
            },
          },
       }
```
这种是一次性获取结果，等待结果期间，你的光标可以自由移动，同时光标旁会有等待的动画

**Comment by shy-robin** [comment]
好的呀，另外我发现个问题，用 `LLMAppHandler` 提供的翻译模块，这里的默认样式底色融为一体了，是不是用边框将输入和输出分隔开比较好？

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/37462906-df0e-4a12-9e7b-44461482bcfb">

**Comment by Kurama622** [comment]
这个模块我也觉得巨丑无比，所以我在新分支中修改了它的默认样式，后面会合并进主分支，大概会长这个样
```

╭─────────────────── 󰊿 Trans ───────────────────╮
│                                               │
│                                               │
├───────────────────────────────────────────────┤
│                                               │
│                                               │
│                                               │
│                                               │
│                                               │
│                                               │
│                                               │
│                                               │
╰───────────────────────────────────────────────╯

```

**Comment by shy-robin** [comment]
我当前用 `chat` 模块比较多，有几个我觉得可以改进的地方我提下哈

1. 每次我 chat 完之后退出弹窗后，再次进入都会定位到一个 current 的会话，每次我都需要手动定位到上次的会话
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/ca11d532-76f3-43d0-9c0e-b7c352605928">

2. 可以支持会话重命名吗？现在这个名称有点难识别
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/681de8fe-29e0-4ed5-a8a2-0fd3812a715b">

3. 生成结果的过程中如果中途退出了，结果就中断了，因为我看 preview 的文件类型是 markdown ，所有这些被中断的文案就会导致 markdown-preview 渲染的样式错乱（比如第一个 ```  后面的代码截断了，没有生成结束的 ```，就会导致后面生成的文案都渲染成代码块）这个我不知道好不好解决。。

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/d769b6e7-ebdb-48ed-84ca-2a7d1447cc7c">

**Comment by shy-robin** [comment]
再加一个，能不能提供一个获取当前模型的方法，以及右侧生成提问和回答的时间
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/0462eb55-fd8a-44fd-bbe8-d7dedbbfa8b5">

**Comment by Kurama622** [comment]
1. 每次 chat 完之后退出弹窗后，再次进入都会定位到一个 current 的会话，每次都需要手动定位到上次的会话
因为退出弹窗意味这对话结束，你需要的是隐藏弹窗。当我们在使用chatgpt或者通义千问网页版的时候，关闭页面再重新进入，也是会打开新的对话页面，这里面的逻辑是一样的。如果你使用<leader>ac打开对话，你再按一遍<leader>ac就是隐藏对话，这个不会定位到current

2. 可以支持会话重命名吗？现在这个名称有点难识别
会话重命名不太好实现，因为不光要改掉文件的名字，还要改掉内存里面一些信息，但是你自己对文件重命名是支持的

3. 生成结果的过程中如果中途退出了，结果就中断了，被中断的文案就会导致 markdown-preview 渲染的样式错乱（比如第一个 ``` 后面的代码截断了，没有生成结束的 ```，就会导致后面生成的文案都渲染成代码块）
如果是不想中途退出又不想等待结果生成，可以使用隐藏会话，方法见1.
如果是对生成结果不满意，手动中断的，可以<C-r>重新生成回答，这样会清除掉前面的回答（你可能需要切换一下会话或者重新打开会话）

**Comment by shy-robin** [comment]
> 你现在用的这个弹窗翻译，是流式输出的版本，但是这种方式窗口大小是固定的，我感觉特别丑。所以后面我开发了一版弹性窗口，根据内容多少调整窗口大小。如果你有兴趣也可以体验一下：
> 
> ```lua
>         spinner = {
>           text = {
>             "󰧞󰧞",
>             "󰧞󰧞",
>             "󰧞󰧞",
>             "󰧞󰧞",
>           },
>           hl = "Title",
>         },
> 
>         app_handler = {
>           WordTranslate = {
>             handler = tools.flexi_handler,
>             prompt = "Translate the following text to Chinese, please only return the translation",
>             opts = {
>               exit_on_move = true,
>               enter_flexible_window = false,
>             },
>           },
>        }
> ```
> 
> 这种是一次性获取结果，等待结果期间，你的光标可以自由移动，同时光标旁会有等待的动画

这个我体验了，效果很棒。但有个问题就是如果我光标移动太快，很容易让弹窗瞬间消失（个人感觉这种翻译结果单独放到单独的 split 窗口比较好，不容易误操作导致消失）


https://github.com/user-attachments/assets/a644d639-1c3b-48dc-b2cb-cbb7a1647e76

**Comment by Kurama622** [comment]
> 再加一个，能不能提供一个获取当前模型的方法，以及右侧生成提问和回答的时间 <img alt="image" width="1005" src="https://private-user-images.githubusercontent.com/59857729/393327126-0462eb55-fd8a-44fd-bbe8-d7dedbbfa8b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDIzMDgsIm5iZiI6MTczMzUwMjAwOCwicGF0aCI6Ii81OTg1NzcyOS8zOTMzMjcxMjYtMDQ2MmViNTUtZmQ4YS00NGZkLWJiZTgtZDdkZWRiYmZhOGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE2MjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhM2ZkM2U4ZDU2NGE4MzY3ZGQzNzMxNGZiYjk3MTI5M2I4NTU2NWJjNWM5NWI2YmMwZThhZTI4N2I5ZTRkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zCCOlIAmaK6xWbeuXRdHzb0KaN-smJgyqrXrifae71s">

获取当前模型，这个不太明白要什么，用什么模型不是我们自己配置的吗，不过可以考虑加一个小窗口展示当前模型的信息。

对话时间展示，我个人感觉用处不大，目前没有考虑加入，或者优先级会比较低。目前改掉一些丑陋的UI对来说，可能更重要，比如你提到的翻译模块

**Comment by Kurama622** [comment]
> 哦哦，`<C-w>` 这种跳转我不太常用，我一般使用 `<C-h/j/k/l>` 进行窗口跳转的，这个我注意一下。

https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm/keymaps.lua 窗口切换快捷键添加上了，你可以自定义预览和输入窗口之间切换的快捷键

**Comment by shy-robin** [comment]
> > 哦哦，`<C-w>` 这种跳转我不太常用，我一般使用 `<C-h/j/k/l>` 进行窗口跳转的，这个我注意一下。
> 
> https://github.com/Kurama622/.lazyvim/blob/main/lua/plugins/llm/keymaps.lua 窗口切换快捷键添加上了，你可以自定义预览和输入窗口之间切换的快捷键

好的，感谢大佬的更新，我更新下试试~ 有反馈我随时同步
